services:
  forger:
    build:
      context: .
    env_file:
      - .env
    environment:
      ACCOUNT_USERNAME: "${ACCOUNT_USERNAME}"
      ACCOUNT_PASSWORD: "${ACCOUNT_PASSWORD}"
      ACCOUNT_EMAIL: "${ACCOUNT_EMAIL}"
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.config/gh:/root/.config/gh:ro
      - ~/.oh-my-zsh:/root/.oh-my-zsh:ro
      - ~/.zshrc:/root/.zshrc:ro
      - ~/Workspace:/workspace
    ports:
      - "2222:22"
